name: dailypulse
description: A personal wellness tracker app for logging daily moods and emotional awareness.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Storage
  shared_preferences: ^2.2.2
  flutter_provider: ^2.1.0
  provider: ^6.1.5+1
  flutter_riverpod: ^2.6.1
  google_sign_in: ^7.1.1
  firebase_auth: ^6.0.1
  
  # Date & Time Formatting
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.21.3+1
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true